# SIMULATION TEST ARTIFACT
version: 0.1
warehouse: bigquery
lineage_sources:
- id: dbt_core
  type: dbt
  manifest_path: target/manifest.json
domains:
  executive-revenue:
    lineage:
    - source: dbt_core
      models:
      - fct_revenue
      - fct_orders
      - stg_orders
      - stg_refunds
      - stg_invoices
      - stg_revenue_recognition
      - dim_customers
      - stg_app_customers
      - dim_date
      - int_customer_identity
      - fct_order_lines
  customers:
    lineage:
    - source: dbt_core
      models:
      - dim_customers
      - fct_orders
      - int_customer_identity
      - fct_identity_resolution_quality
      - dim_date
  marketing:
    lineage:
    - source: dbt_core
      models:
      - fct_marketing_spend
      - fct_order_lines
      - fct_orders
      - dim_products
      - dim_date
  subscriptions:
    lineage:
    - source: dbt_core
      models:
      - fct_subscriptions
      - dim_plans
      - stg_plan_prices
      - dim_date
